#!/bin/bash
# Copy the committed table artifacts (analysis/tables/, generated by
# analysis/make_tables.py) into paper/generated/, promoting each {table}
# float to a full-width {table*} for the two-column ACL layout. Numbers are
# never edited here — regenerate the artifacts to change them.
# Run from paper/ before pdflatex.
set -e
cd "$(dirname "$0")"
mkdir -p generated
for f in ../analysis/tables/T*.tex; do
  sed -e 's/\\begin{table}\[t\]/\\begin{table*}[t]/' \
      -e 's/\\end{table}/\\end{table*}/' "$f" > "generated/$(basename "$f")"
done
echo "generated/: $(ls generated | tr '\n' ' ')"
